### ISSUE TITLE
Default ruleset does not delete script, style, etc. tags

### ISSUE THREAD

**Issue by wezm** [andy128k/sanitize-html-rs#1]
[In sanitize these tags are deleted entirely](https://github.com/rgrove/sanitize/blob/245c705bac3723c439f2025a090ca751635c23c2/lib/sanitize/config/default.rb#L77). Would you be open to a PR that adds the following to the DEFAULT ruleset?

    .delete("iframe")
    .delete("noembed")
    .delete("noframes")
    .delete("noscript")
    .delete("script")
    .delete("style")

My motivation is that `DEFAULT` is basically a "strip tags" mode, where you want to get rid of all tags but retain well formatted content (as far as whitespace goes). It seems that the content of `<script>`, `<style>`, etc. are not useful in this context.

**Comment by andy128k** [comment]
@wezm PRs are welcomed.
